### ISSUE TITLE
Init argument names should not use Pin

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_IL91874#14]
We recently changed argument names for initializing the ESP32SPI library to use the suffix `_dio` rather than `_pin` because the arguments need to be instantiated `DigitalInOut` objects, not `microcontroller.Pin` objects.

See: https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/issues/121

This library uses the same `*_pin` names for it's arguments which are also expected to the `DigitalInOut`s rather than `Pin`s.

I think we'll want to change the names here and any other libraries that have `_pin` to keep things consistent across libraries.

**Comment by tekktrik** [comment]
Is this correct?  I don't see reference to `*_pin` arguments, or do they come from `displayio.EPaperDisplay`?

**Comment by tekktrik** [comment]
@FoamyGuy I think this should be closed since it doesn't seem to be an issue with this library.  There aren't any pin/IO arguments to the main class in this library, and even the base `EPaperDisplay` seems to only have one `_pin` argument which does take a `Pin` object according to the [docs](https://docs.circuitpython.org/en/latest/shared-bindings/epaperdisplay/index.html#epaperdisplay.EPaperDisplay).

**Comment by FoamyGuy** [comment]
Yep, I don't see any DigitalInOut's either, closing this
